sudo: required
services:
  - docker

before_install:
  - docker build -t nishitav19/react-test -f ./webapp/Dockerfile.dev ./webapp

script:
  - docker run -e CI=true nishitav19/react-test npm test -- --coverage

after_success:
  - docker build -t nishitav19/multi-webapp ./webapp
  - docker build -t nishitav19/multi-nginx ./nginx
  - docker build -t nishitav19/multi-api-server ./api-server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  # Take those images and push them to docker hub
  - docker push nishitav19/multi-webapp
  - docker push nishitav19/multi-nginx
  - docker push nishitav19/multi-api-server
